warn = [
    "clippy::pedantic",
    "clippy::nursery",
    "clippy::cargo",
]

allow = [
    "clippy::module_name_repetitions",
    "clippy::missing_errors_doc",
    "clippy::missing_panics_doc",
    "clippy::must_use_candidate",
    "clippy::multiple_crate_versions",
    "clippy::cargo_common_metadata",
    "clippy::cast_possible_truncation",
    "clippy::cast_possible_wrap",
    "clippy::cast_sign_loss",
    "clippy::cast_lossless",
    "clippy::cast_precision_loss",
    "clippy::doc_markdown",
    "clippy::missing_const_for_fn",
    "clippy::redundant_clone",
    "clippy::redundant_pub_crate",
    "clippy::option_if_let_else",
    "clippy::ref_option",
    "clippy::or_fun_call",
    "clippy::semicolon_if_nothing_returned",
    "clippy::uninlined_format_args",
    "clippy::too_many_lines",
    "clippy::unused_async",
    "clippy::unnecessary_wraps",
    "clippy::unnecessary_debug_formatting",
    "clippy::needless_pass_by_value",
    "clippy::cognitive_complexity",
    "clippy::use_self",
    "clippy::used_underscore_binding",
    "clippy::return_self_not_must_use",
    "clippy::ignored_unit_patterns",
    "clippy::equatable_if_let",
    "clippy::default_trait_access",
]
