[package]
name = "nsp-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
name = "nsp_api"
path = "src/lib.rs"

[dependencies]
nsp-core = { path = "../core" }
nsp-db = { path = "../db" }
nsp-netctl = { path = "../netctl" }
nsp-proxy-driver = { path = "../proxy-driver" }
nsp-ss-driver = { path = "../ss-driver" }
nsp-wg-driver = { path = "../wg-driver" }

axum = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true }
ipnetwork = { workspace = true }
mime = { workspace = true }
mime_guess = { workspace = true }
rust-embed = { workspace = true }
secrecy = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tower = { workspace = true, features = ["util"] }
