/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth.index'
import { Route as AuthSettingsRouteImport } from './routes/_auth.settings'
import { Route as AuthIptablesRouteImport } from './routes/_auth.iptables'
import { Route as AuthAuditRouteImport } from './routes/_auth.audit'
import { Route as AuthUsersIndexRouteImport } from './routes/_auth.users.index'
import { Route as AuthServicesIndexRouteImport } from './routes/_auth.services.index'
import { Route as AuthUsersNameRouteImport } from './routes/_auth.users.$name'
import { Route as AuthServicesIdRouteImport } from './routes/_auth.services.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthIptablesRoute = AuthIptablesRouteImport.update({
  id: '/iptables',
  path: '/iptables',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAuditRoute = AuthAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsersIndexRoute = AuthUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthServicesIndexRoute = AuthServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsersNameRoute = AuthUsersNameRouteImport.update({
  id: '/users/$name',
  path: '/users/$name',
  getParentRoute: () => AuthRoute,
} as any)
const AuthServicesIdRoute = AuthServicesIdRouteImport.update({
  id: '/services/$id',
  path: '/services/$id',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/audit': typeof AuthAuditRoute
  '/iptables': typeof AuthIptablesRoute
  '/settings': typeof AuthSettingsRoute
  '/services/$id': typeof AuthServicesIdRoute
  '/users/$name': typeof AuthUsersNameRoute
  '/services/': typeof AuthServicesIndexRoute
  '/users/': typeof AuthUsersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/audit': typeof AuthAuditRoute
  '/iptables': typeof AuthIptablesRoute
  '/settings': typeof AuthSettingsRoute
  '/': typeof AuthIndexRoute
  '/services/$id': typeof AuthServicesIdRoute
  '/users/$name': typeof AuthUsersNameRoute
  '/services': typeof AuthServicesIndexRoute
  '/users': typeof AuthUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/audit': typeof AuthAuditRoute
  '/_auth/iptables': typeof AuthIptablesRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/services/$id': typeof AuthServicesIdRoute
  '/_auth/users/$name': typeof AuthUsersNameRoute
  '/_auth/services/': typeof AuthServicesIndexRoute
  '/_auth/users/': typeof AuthUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audit'
    | '/iptables'
    | '/settings'
    | '/services/$id'
    | '/users/$name'
    | '/services/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/audit'
    | '/iptables'
    | '/settings'
    | '/'
    | '/services/$id'
    | '/users/$name'
    | '/services'
    | '/users'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/audit'
    | '/_auth/iptables'
    | '/_auth/settings'
    | '/_auth/'
    | '/_auth/services/$id'
    | '/_auth/users/$name'
    | '/_auth/services/'
    | '/_auth/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/iptables': {
      id: '/_auth/iptables'
      path: '/iptables'
      fullPath: '/iptables'
      preLoaderRoute: typeof AuthIptablesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/audit': {
      id: '/_auth/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthAuditRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/users/': {
      id: '/_auth/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthUsersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/services/': {
      id: '/_auth/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof AuthServicesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/users/$name': {
      id: '/_auth/users/$name'
      path: '/users/$name'
      fullPath: '/users/$name'
      preLoaderRoute: typeof AuthUsersNameRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/services/$id': {
      id: '/_auth/services/$id'
      path: '/services/$id'
      fullPath: '/services/$id'
      preLoaderRoute: typeof AuthServicesIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAuditRoute: typeof AuthAuditRoute
  AuthIptablesRoute: typeof AuthIptablesRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthServicesIdRoute: typeof AuthServicesIdRoute
  AuthUsersNameRoute: typeof AuthUsersNameRoute
  AuthServicesIndexRoute: typeof AuthServicesIndexRoute
  AuthUsersIndexRoute: typeof AuthUsersIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuditRoute: AuthAuditRoute,
  AuthIptablesRoute: AuthIptablesRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthServicesIdRoute: AuthServicesIdRoute,
  AuthUsersNameRoute: AuthUsersNameRoute,
  AuthServicesIndexRoute: AuthServicesIndexRoute,
  AuthUsersIndexRoute: AuthUsersIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
